site_name: 'Subaerial Drainage System Model (SaDS)'
theme:
    name: material
    icon:
      logo: fontawesome/solid/mountain
    palette:
      - sheme: default
        primary: cyan
        accent: red
    features:
      - toc.integrate
      - navigation.tabs

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript:
        - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
        - 'javascripts/extra.js'
nav:
        - Home: index.md
        - Getting started:
                - Startup guide: startup.md
                - Configuration: configuration.md
        - Tutorial:
            - tutorial.md

markdown_extensions:
        - pymdownx.highlight
        - pymdownx.superfences

docs_dir: docs_source/
site_dir: docs/
